### ISSUE TITLE
WS issue sending after disconnected

### ISSUE THREAD

**Issue by ColdSauce** [goonism/hyperproxy#31]
Getting this error

`Error: cannot call send() while not connected\n    at W3CWebSocket.send (/root/hyperproxy/node_modules/websocket/lib/W3CWebSocket.js:111:15)\n    at sockets.forEach (/root/hyperproxy/node_modules/signalhubws/index.js:90:12)\n    at Array.forEach (<anonymous>)\n    at SignalhubWs.broadcast (/root/hyperproxy/node_modules/signalhubws/index.js:89:16)\n    at connect (/root/hyperproxy/node_modules/webrtc-swarm/index.js:179:7)\n    at ontimeout (timers.js:466:11)\n    at tryOnTimeout (timers.js:304:5)\n    at Timer.listOnTimeout (timers.js:267:5)
`

Need to figure out why this is happening.

**Comment by ColdSauce** [comment]
Seems to be because the file that I was requesting was too large to fit inside a single web socket frame. Instead of fixing that issue, I think we should stop relying on web socket broadcasts as the way to transfer data. The right way to fix this is by doing #33
